// Spike candidate A: dave/jennifer programmatic AST emission.
//
// This runner produces the same User struct + Validate() output as
// spike/template/main.go, but builds the file via Jennifer's typed AST.
// Jennifer's headline win is automatic import management: every Qual(path,
// name) call adds the corresponding import to the file's import block, with
// no conditional bookkeeping at the call site. See spike/README.md and
// PROJECT.md "Key Decisions" for the comparison.
package main

import (
	"github.com/dave/jennifer/jen"
)

// userData mirrors the spike/template fixture struct shape so both runners
// receive an apples-to-apples toggle set. The runners are deliberately
// independent (no shared module) per 00-RESEARCH.md Open Question 2.
type userData struct {
	HasTime   bool
	HasRegexp bool
	HasErrors bool
	HasSlices bool
}

func main() {
	fixture := userData{
		HasTime:   true,
		HasRegexp: true,
		HasErrors: true,
		HasSlices: true,
	}

	f := jen.NewFile("domain")
	f.HeaderComment("Code generated by spike/jennifer. DO NOT EDIT.")

	// Package-level regex used by Validate. Qual("regexp", ...) auto-adds
	// the "regexp" import.
	if fixture.HasRegexp {
		f.Var().Id("userNameRegex").Op("=").Qual("regexp", "MustCompile").Call(
			jen.Lit(`^[A-Za-z0-9._-]{1,64}$`),
		)
	}

	// type UserEmail struct { ... }
	f.Type().Id("UserEmail").Struct(
		jen.Id("Value").String().Tag(map[string]string{"json": "value"}),
		jen.Id("Type").String().Tag(map[string]string{"json": "type"}),
		jen.Id("Primary").Bool().Tag(map[string]string{"json": "primary"}),
	)

	// type User struct { ... }
	userFields := []jen.Code{
		jen.Id("ID").String().Tag(map[string]string{"json": "id"}),
		jen.Id("UserName").String().Tag(map[string]string{"json": "userName"}),
		jen.Id("Title").String().Tag(map[string]string{"json": "title"}),
	}
	if fixture.HasTime {
		userFields = append(userFields,
			jen.Id("Created").Qual("time", "Time").Tag(map[string]string{"json": "created"}),
		)
	}
	userFields = append(userFields,
		jen.Id("Emails").Index().Id("UserEmail").Tag(map[string]string{"json": "emails"}),
	)
	f.Type().Id("User").Struct(userFields...)

	// func (u *User) Validate() error { ... }
	body := []jen.Code{
		jen.If(jen.Id("u").Dot("UserName").Op("==").Lit("")).Block(
			jen.Return(jen.Qual("fmt", "Errorf").Call(jen.Lit("userName is required"))),
		),
	}
	if fixture.HasRegexp {
		body = append(body,
			jen.If(jen.Op("!").Id("userNameRegex").Dot("MatchString").Call(jen.Id("u").Dot("UserName"))).Block(
				jen.Return(jen.Qual("fmt", "Errorf").Call(jen.Lit("userName does not match required pattern"))),
			),
		)
	}
	if fixture.HasSlices {
		body = append(body,
			jen.If(
				jen.Id("u").Dot("Title").Op("!=").Lit("").
					Op("&&").
					Op("!").Qual("slices", "Contains").Call(
					jen.Index().String().Values(jen.Lit("Mr"), jen.Lit("Mrs"), jen.Lit("Ms"), jen.Lit("Dr")),
					jen.Id("u").Dot("Title"),
				),
			).Block(
				jen.Return(jen.Qual("fmt", "Errorf").Call(jen.Lit("title must be one of canonicalValues: Mr, Mrs, Ms, Dr"))),
			),
		)
	}
	body = append(body,
		jen.Id("primaryCount").Op(":=").Lit(0),
		jen.For(jen.Id("i").Op(":=").Range().Id("u").Dot("Emails")).Block(
			jen.If(jen.Id("u").Dot("Emails").Index(jen.Id("i")).Dot("Primary")).Block(
				jen.Id("primaryCount").Op("++"),
			),
		),
		jen.If(jen.Id("primaryCount").Op(">").Lit(1)).Block(
			jen.Return(jen.Qual("fmt", "Errorf").Call(jen.Lit("at most one email may be marked primary"))),
		),
		jen.Return(jen.Nil()),
	)

	f.Func().
		Params(jen.Id("u").Op("*").Id("User")).
		Id("Validate").Params().
		Error().
		Block(body...)

	// f.Save runs go/format internally before writing.
	if err := f.Save("output/user_gen.go"); err != nil {
		panic(err)
	}
}
