// Code generated by spike/jennifer. DO NOT EDIT.

package domain

import (
	"fmt"
	"regexp"
	"slices"
	"time"
)

var userNameRegex = regexp.MustCompile("^[A-Za-z0-9._-]{1,64}$")

type UserEmail struct {
	Value   string `json:"value"`
	Type    string `json:"type"`
	Primary bool   `json:"primary"`
}
type User struct {
	ID       string      `json:"id"`
	UserName string      `json:"userName"`
	Title    string      `json:"title"`
	Created  time.Time   `json:"created"`
	Emails   []UserEmail `json:"emails"`
}

func (u *User) Validate() error {
	if u.UserName == "" {
		return fmt.Errorf("userName is required")
	}
	if !userNameRegex.MatchString(u.UserName) {
		return fmt.Errorf("userName does not match required pattern")
	}
	if u.Title != "" && !slices.Contains([]string{"Mr", "Mrs", "Ms", "Dr"}, u.Title) {
		return fmt.Errorf("title must be one of canonicalValues: Mr, Mrs, Ms, Dr")
	}
	primaryCount := 0
	for i := range u.Emails {
		if u.Emails[i].Primary {
			primaryCount++
		}
	}
	if primaryCount > 1 {
		return fmt.Errorf("at most one email may be marked primary")
	}
	return nil
}
